apolloCloud/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #the default app is users
    url(r'', include('users.urls', namespace='users')),
    url(r'^forecast/', include('forecast.urls', namespace='forecast')),
]

forecast/urls.py
"""define the url mode of forecast app""" 

from django.conf.urls import url

from . import views

urlpatterns=[
    #main page for each user, containing the upload records
    url(r'^$', views.records, name='records'),
    #upload page
    url(r'^upload/$', views.upload, name='upload'),
    #detailed description for a single upload item
    url(r'^item/(?P<upload_id>\d+)/$', views.item, name='item'),
    #the link for download the primary data file
    url(r'^itemdownload/(?P<upload_id>\d+)/$', views.itemdownload, name='itemdownload'),
    # the link for downloading the result file
    url(r'^resultFile/(?P<fileUrl>.+)/$', views.resultFile, name='resultFile'),
]

users/urls.py
"""define the urls mode of urls app"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns=[
    #login page, the views.function use the provided one
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    #index page
    url(r'^$', views.index, name='index'),
    #register page
    url(r'^register/$', views.register, name='register'),
    #log out page
    url(r'^logout/$', views.logout_view, name='logout'),
]

forecast/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.owner.id, filename)


def user_file_name(instance, filename):
    return '{0}'.format(filename)


class Upload(models.Model):
    """the upload record item for each forecast"""
    owner = models.ForeignKey(User)
    FORECASTPERIOD = (
        ('s', 'short term'),
        ('m', 'medium term'),
        ('l', 'long term'),
    )
    FORECASTMETHOD = (
        ('ann', 'neural network'),
        ('svm', 'support vector machine'),
        ('mps', 'multiple proportion smoothing method')
    )
    # the max_length limits the length of key
    # blank & default is to remove the '---' in the model form;
    # the fist parameter is for the label of the form
    forecastperiod = models.CharField("Forecasting period", max_length=1, \
                                      choices=FORECASTPERIOD, blank=False,
                                      default='m')
    forecastmethod = models.CharField("Forecasting method", max_length=3, \
                                      choices=FORECASTMETHOD, blank=False,
                                      default='ann')
    userfiles = models.FileField(upload_to=user_directory_path)
    uploadName = models.CharField("Upload File Name", max_length=100) # the name of user uoload file
    firstDay = models.CharField("First Day for forecasting (example:2014/10/20)", max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        """return the string format of the upload record"""
        return str(self.date_added)

forecast/forms.py
from django import forms

from .models import Upload

class UploadForm(forms.ModelForm):
    """the form for upload files"""
    class Meta:
        model = Upload
        fields = ['userfiles','uploadName','firstDay','forecastperiod','forecastmethod']
        labels = {'text': 'upload *.csv file'}

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.owner.id, filename)

# class UploadForm(forms.Form):
#     """ the form for uploading files"""
#     FORECASTPERIOD = (
#         ('s', 'short term'),
#         ('m', 'medium term'),
#         ('l', 'long term'),
#     )
#     FORECASTMETHOD = (
#         ('ann', 'neural network'),
#         ('svm', 'support vector machine'),
#         ('mps', 'multiple proportion smoothing method')
#     )
#     uploadName = forms.CharField(max_length=100)
#     file = forms.FileField(upload_to=user_directory_path)
#     forecastperiod = forms.CharField("Forecasting period", max_length=1, \
#                                       choices=FORECASTPERIOD, blank=False,
#                                       default='m')
#     forecastmethod = forms.CharField("Forecasting method", max_length=3, \
#                                       choices=FORECASTMETHOD, blank=False,
#                                       default='ann')

forecast/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import os

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse,Http404, StreamingHttpResponse
from django.core.urlresolvers import reverse
from django import forms
from django.contrib.auth.decorators import login_required

from forecast.models import Upload
from forecast.forms import UploadForm

from prophetMethod.mps import *

# Create your views here.

@login_required
def records(request):
    """show all records of a specific user"""
    records = Upload.objects.filter(owner=request.user).order_by('-date_added')
    context = {'records':records}
    return render(request, 'forecast/index.html', context)


@login_required
def upload(request):
    """the page for upload files containing the data"""
    if request.method != 'POST':
        uploadForm = UploadForm()
    else:
        uploadForm = UploadForm(request.POST, request.FILES)
        if uploadForm.is_valid():
            new_uploadForm = uploadForm.save(commit=False)
            new_uploadForm.owner = request.user
            new_uploadForm.save()
            return HttpResponseRedirect(reverse('forecast:records'))
            #the page to redirect should be modified, i.e., the records or result page
    context = {'uploadForm':uploadForm}
    return render(request, 'forecast/upload.html', context)

@login_required
def item(request, upload_id):
    """the detailed description for a upload item"""
    upload = Upload.objects.get(id=upload_id)
    if upload.owner != request.user:
        raise Http404
    # do the calculation
    day = 0
    method = "mps"
    if upload.forecastperiod == "s":
        day = 1
    elif upload.forecastperiod == "m":
        day = 7
    else:
        day = 14
    dataJson = forecast_more(upload.firstDay, day,"upload/"+str(upload.userfiles), "upload/"+str(upload.userfiles)+"_result.csv")
    dataJson = json.loads(dataJson)
    resultUrl = "http://localhost:8000/forecast/resultFile/upload/"+str(upload.userfiles)+"_result.csv"
    #resultDownUrlHead = "forecast/resultDownload/"
    context = {'upload':upload, 'dataJson':dataJson, 'resultUrl':resultUrl,'userfiles':str(upload.userfiles)}
    return render(request, 'forecast/item.html',context)

@login_required #this is not necessary
def itemdownload(request,upload_id):
    def file_iterator(file_name,chunk_size=512):
        with open(file_name) as f:
            while True:
                c = f.read(chunk_size)
                if c:
                    yield c
                else:
                    break

    upload = Upload.objects.get(id=upload_id)
    filename='upload' + os.sep + str(upload.userfiles)  #this may needed changing if the location of files downloading is varing
    response = StreamingHttpResponse(file_iterator(filename))
    response['Content-Type'] = 'application/octet-stream'
    response['Content--Disposition'] = 'attachment;filename="{0}"'.format(filename)

    return response

@login_required
def resultFile(request, fileUrl):
    def file_iterator(file_name,chunk_size=512):
        with open(file_name) as f:
            while True:
                c = f.read(chunk_size)
                if c:
                    yield c
                else:
                    break

    response = StreamingHttpResponse(file_iterator(fileUrl))
    response['Content-Type'] = 'application/octet-stream'
    response['Content--Disposition'] = 'attachment;filename="{0}"'.format(fileUrl)

    return response

forecast/templates/forecast/index.html
{% extends "users/base.html" %}

{% comment "primary codes" %}
{% block content %}
    <p>Forecasts records:</p>
    <ul>
        {% for upload in records %}
            <li>
                <p>{{ upload.date_added|date:'M d, Y H:i' }}</p> - 
                <a href="{% url 'forecast:itemdownload' upload.id %}">{{upload.userfiles}}</a> - 
                <a href="{% url 'forecast:item' upload.id %}">detailed description</a> 
            </li>
            {% empty %}
            <li>
                There are no records for you.
            </li>
        {% endfor %}
    </ul>

{% endblock %}
{% endcomment %}

{% load bootstrap3 %}

{% block header %}
    <h2>Forecasts records</h2>
{% endblock header%}

{% block content %}
<ul>
{% for upload in records %}
    <div class="panel panel-info">
         <div class="panel-heading">
           <h3 class="panel-title">{{ upload.date_added|date:'M d, Y H:i' }}</h3>
         </div>
         <div class="panel-body">
             {#upload.userfiles|slugify|slice:"6:"#}
           <a href="{% url 'forecast:itemdownload' upload.id %}">{{upload.uploadName}}</a> -    {#temporary, need to change#}
     <a href="{% url 'forecast:item' upload.id %}">detailed description</a> 
         </div>
    </div>
{% empty %}
    <li>There are no records for you.</li>
{% endfor %}
</ul>

<h3><a href="{% url 'forecast:upload' %}">Start a new forecast item</a></h3>


{% endblock content %}

forecast/templates/forecast/item.html
{% extends "users/base.html" %}
{% load bootstrap3 %}
{% block content %}

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">{{upload.date_added}}</div>
  <div class="panel-body">
    <p><p><em>some other detailed descriptions for this forecast info, including the upload file, forecast parameters, the download link of both upload file and download file, & the visualized plot of the data</em></p></p>
  </div>

  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item">Upload File : {{upload.uploadName}}</li>
    <li class="list-group-item">First Day for forecasting : {{ upload.firstDay }}</li>
    <li class="list-group-item">Forecast Period : {{upload.forecastperiod}}</li>
    <li class="list-group-item">Forecast Method : {{upload.forecastmethod}}</li>
    <li class="list-group-item">Result file : <a href={{ resultUrl }}> downloading result file</a></li>
  </ul>
</div>
    <h3> result file content</h3>
    {%  for line in dataJson %}
        <li> {{ line }}</li>
    {% endfor %}
{% endblock content %}

forecast/templates/forecast/upload.html
{% extends "users/base.html" %}

{% comment "primary code" %}

<!-- this file is the page for upload new data file for forecasting -->


{% block content %}

    <h1>start a new forecast item</h1>
    <form action="{% url 'forecast:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ uploadForm.as_p }}
    <button name="Submit">ok!</button>
    </form>

{% endblock content %}
{% endcomment %}

{% load bootstrap3 %}

{% block header %}
<h2>start a new forecast item</h2>
{% endblock header%}

{% block content%}
    <form action="{% url 'forecast:upload' %}" method="post" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {% bootstrap_form uploadForm%} 
    
    <button name="Submit">ok!</button>
     <input type="hidden" name="next" value="{% url 'users:index' %}"/>
    </form>
    
{% endblock content%}