apolloCloud/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #the default app is users
    url(r'', include('users.urls', namespace='users')),
    url(r'^forecast/', include('forecast.urls', namespace='forecast')),
]

forecast/urls.py
"""define the url mode of forecast app""" 

from django.conf.urls import url

from . import views

urlpatterns=[
    #main page for each user, containing the upload records
    url(r'^$', views.records, name='records'),
    #upload page
    url(r'^upload/$', views.upload, name='upload'),
    #detailed description for a single upload item
    url(r'^item/(?P<upload_id>\d+)/$', views.item, name='item'),
    #the link for download the primary data file
    url(r'^itemdownload/(?P<upload_id>\d+)/$', views.itemdownload, name='itemdownload'),
    # the link for downloading the result file
    url(r'^resultFile/(?P<fileUrl>.+)/$', views.resultFile, name='resultFile'),
]

users/urls.py
"""define the urls mode of urls app"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns=[
    #login page, the views.function use the provided one
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    #index page
    url(r'^$', views.index, name='index'),
    #register page
    url(r'^register/$', views.register, name='register'),
    #log out page
    url(r'^logout/$', views.logout_view, name='logout'),
]

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    """the main page of apolloCloud platform"""
    return render(request, 'users/index.html')

def logout_view(request):
    """log out and redirect to the index page"""
    logout(request)
    return HttpResponseRedirect(reverse('users:index'))

def register(request):
    """register"""
    if request.method != 'POST':
        #show the empty register form
        form = UserCreationForm()
    else:
        #process the register form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #let the user login automatically, and redirect to the main page
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('users:index'))

    context = {'form':form}
    return render(request,'users/register.html', context)

users/templates/users/base.html
{% comment "primary code" %}
<h1>
    apolloCloud
</h1>

<p>
    <a href="{% url 'users:index' %}">Main page</a> -
    {% if user.is_authenticated %}
        Hello, {{user.username}} - 
        <a href="{% url 'users:logout' %}">Log out</a> - 
        <a href="{% url 'forecast:records' %}">person main page</a> -
        <a href="{% url 'forecast:upload' %}">start a new forecast item</a>
    {% else %}
        <a href="{% url 'users:login' %}">Log in</a> -
        <a href="{% url 'users:register' %}">Register</a>
    {% endif %}
</p>

{% block content %}

{% endblock content %}

{% endcomment %}

{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>ApolloCloud</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
        

        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapsed" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'users:index' %}">
                        Main page </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a>Hello, {{ user.username }}</a></li>
                            <li><a href="{% url 'users:logout' %}">log out</a></li> 
                            <li><a href="{% url 'forecast:records' %}">personal main page</a></li> 
                            <li><a href="{% url 'forecast:upload' %}">start a new forecast item</a></li> 
                        {% else %}
                            <li><a href="{% url 'users:register' %}">register</a></li>
                            <li><a href="{% url 'users:login' %}">log in </a></li>
                        {% endif %}
                    </ul>
                </div> 

            </div>
        </nav>

        <div class="container">

            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>

        </div> 

    </body>
</html>

users/templates/users/index.html
{% extends "users/base.html" %}

{% comment "primary codes" %}
{% extends "users/base.html" %}

{% block content %}
    
    <p>ApolloCloud is a platform that helps you do the forecast easily.</p>

    <p>It is a sharp tool you can ever imagine! </p>

{% endblock content %}

{% endcomment %}


{% load bootstrap3 %}






{% block header %}

<div class="page-header">
  <h1>ApolloCloud <small>Do the forecasting automatically, easily for you</small></h1>
</div>

{% endblock header %}

{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Features</h3>
  </div>
  <div class="panel-body">
     <p>ApolloCloud is a platform that helps you do the forecast easily.</p>

    <p>It is a sharp tool you can ever imagine! </p>
  </div>
</div>


     
{% endblock content %}

users/templates/users/login.html
{% extends "users/base.html" %}

{% comment "primary code" %}
{% block content %}
   {% if forms.errors %}
   <p>Your username and your password didn't match. Please try again.</p>
   {% endif %}

   <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">log in</button>
    <!-- return to the users/index.html -->
    <input type="hidden" name="next" value="{% url 'users:index' %}" />
    </form>
{% endblock content %}

{% endcomment%}

 {% load bootstrap3 %} 

 {% block header %}
    <h2>Log in to your account. </h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'users:login' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'users:index' %}"/>
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "users/base.html" %}

{% comment "primary codes" %}
{% block content %}

    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="Submit">register</button>
        <input type="hidden" name="next" value="{% url 'users:index' %}" />
    </form>
{% endblock content %}
{% endcomment %}

{% load bootstrap3 %}

{% block header %}
    <h2>Register</h2>
{% endblock header%}

{% block content %}

    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}     
        <button name="submit" class="btn btn-primary">register</button>
        {% endbuttons %} 
        <input type="hidden" name="next" value="{% url 'users:index' %}" />
    </form>
{% endblock content %}